### ISSUE TITLE
Empty profile for guest

### ISSUE THREAD

**Issue by letopisec3** [nextcloud/social#1160]
Describe the bug
my profile is empty for guests  

To Reproduce
go to address
https://example.com/index.php/apps/social/@name/
or
https://example.com/index.php/apps/social/@name@example.com/
![изображение](https://user-images.githubusercontent.com/36674563/102001722-4912d080-3d06-11eb-88fc-b15bcdb5b06f.png)

**Comment by aliceinwire** [comment]
same here

**Comment by ShGKme** [comment]
Error from the console:
```
[ERROR] Files_PDFViewer: But this does not appear to be a public page
    at sentry.js?v=ec69d915-1762:2

TypeError: Cannot read properties of undefined (reading 'acct')
    at i.<anonymous> (Profile.vue?c66d:1:357)
    at e._render (vue.runtime.esm.js:2684:28)
    at i.r (vue.runtime.esm.js:3875:27)
    at e.get (vue.runtime.esm.js:3446:33)
    at e.run (vue.runtime.esm.js:3522:30)
    at yn (vue.runtime.esm.js:4121:17)
    at Array.<anonymous> (vue.runtime.esm.js:3143:20)
    at It **(vue.runtime.esm.js:3065:16)**
    
Failed to load resource: the server responded with a status of 401 ()
    api/v1/accounts/relationships?id[]=<NUMBER>

[ERROR] social: Failed to load relationship info
    at sentry.js?v=ec69d915-1762:2
```

**Comment by pfmephisto** [comment]
same here
