### ISSUE TITLE
could not extract app social

### ISSUE THREAD

**Issue by wesleyehowell** [nextcloud/social#1203]
Trying to install the app into Ubuntu 20.04 Nextcloud snap, 20.0.7snap1 and I'm told it couldn't extract the app.

I'm using Ubuntu 20.04, with Firefox 85.

Nextcloud log:

Error | settings | Exception: Could not extract app social/snap/nextcloud/26119/htdocs/apps/settings/lib/Controller/AppSettingsController.php - line 445: OC\Installer->downloadApp("social")/snap/nextcloud/26119/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 169: OCA\Settings\Controller\AppSettingsController->enableApps([ "social"], [])/snap/nextcloud/26119/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 100: OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings ... {}, "enableApps")/snap/nextcloud/26119/htdocs/lib/private/AppFramework/App.php - line 152: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings ... {}, "enableApps")/snap/nextcloud/26119/htdocs/lib/private/Route/Router.php - line 309: OC\AppFramework\App::main("OCA\\Settin ... r", "enableApps", OC\AppFramew ... {}, { _route: "s ... "})/snap/nextcloud/26119/htdocs/lib/base.php - line 1008: OC\Route\Router->match("/settings/apps/enable")/snap/nextcloud/26119/htdocs/index.php - line 37: OC::handleRequest()
-- | -- | --

End of section

**Comment by jaitaiwan** [comment]
I'm also seeing the same thing

**Comment by Aarontheissueguy** [comment]
Same issue here

**Comment by senooken** [comment]
Hi. I had same error too on Nextcloud 20.0.7 git. I avoided this error by following manual install.

```
cd apps
wget https://github.com/nextcloud/social/releases/download/v0.4.2/social-0.4.2.tar.gz
tar -xf apps/social-0.4.2.tar.gz
cd ..
php occ app:enable social
```

**Comment by Aarontheissueguy** [comment]
How would one do this if he uses the snap.

**Comment by Ascariota** [comment]
I have also this issue 

`Exception: Could not extract app social
/var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php - line 445:

OC\Installer->downloadApp()

/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:

OCA\Settings\Controller\AppSettingsController->enableApps()

/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

OC\AppFramework\Http\Dispatcher->executeController()

/var/www/nextcloud/lib/private/AppFramework/App.php - line 152:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/nextcloud/lib/private/Route/Router.php - line 309:

OC\AppFramework\App::main()

/var/www/nextcloud/lib/base.php - line 1008:

OC\Route\Router->match()

/var/www/nextcloud/index.php - line 37:

OC::handleRequest()`

**Comment by jduncan8142** [comment]
I was able to correct this by increasing the memory_limit in php.ini file and then doing restart on php service. 

`systemctl status php7.4-fpm.service`

Tried this after attempting to enable from cli with occ enable:app and getting the below error:

`PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 405504 bytes) in /var/www/html/3rdparty/composer/autoload_real.php on line 35`

**Comment by pflegende** [comment]
same thing

Nextcloud version: 19.0.9 - 19.0.9.1

Betriebssystem: | Linux 4.15.0-112-generic x86_64
-- | --
Speicher: | 3.85 GB


---

 RAM: Gesamt: 3,9 GB - Aktuelle Nutzung: 1,7 GB


---

Details:

Operating system: Linux 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64

Webserver: Apache (fpm-fcgi)

Database: mysql 10.1.47

PHP version: 7.2.24-0ubuntu0.18.04.7

**Comment by pflegende** [comment]
also upd to NC 20.0.8 made it not better

**Comment by almereyda** [comment]
The same issue happens on Ubuntu 20.04 arm64 on a RPi4 w/ 4 GiB RAM in a container.

```
# docker-compose exec -u 82 app sh
/var/www/html $ ./occ app:install social
Error: Could not extract app social: Out-of-path file extraction {/tmp/oc_tmp_GhfJMa-folder/social/vendor/bin/parallel-lint --> ../jakub-onderka/php-parallel-lint/parallel-lint}

```

**Comment by tayduivn** [comment]
Open files in  apps/social/lib/Migration then replace data type start with Type::   to corresponding data type in database system.
Example I use mysql, so I replace Type::SMALLINT to 'smallint'  and then enable the app

**Comment by korla-plankton** [comment]
Fresh install of Nextcloud 21.0.1. Using directions at https://docs.nextcloud.com/server/21/admin_manual/installation/example_centos.html
I don't have an apps/social/... directory.
Command and output (run as webserver user):
```
bash-4.4$ ./occ app:enable social
Could not extract app social: Out-of-path file extraction {/tmp/oc_tmp_cJAY4b-folder/social/vendor/bin/parallel-lint --> ../jakub-onderka/php-parallel-lint/parallel-lint}
```
I get the same message if I try and do it through the web interface.
From nextcloud.log:
```
{
  "reqId": "*****",
  "level": 3,
  "time": "2021-04-10T21:05:05+00:00",
  "remoteAddr": "*****",
  "user": "*****",
  "app": "settings",
  "method": "POST",
  "url": "/index.php/settings/apps/enable",
  "message": {
    "Exception": "Exception",
    "Message": "Could not extract app social: Out-of-path file extraction {/tmp/oc_tmp_zuSR5S-folder/social/vendor/bin/parallel-lint --> ../jakub-onderka/php-parallel-lint/parallel-lint}",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/nextcloud/apps/settings/lib/Controller/AppSettingsController.php",
        "line": 445,
        "function": "downloadApp",
        "class": "OC\\Installer",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 218,
        "function": "enableApps",
        "class": "OCA\\Settings\\Controller\\AppSettingsController",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 127,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/AppFramework/App.php",
        "line": 157,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/Route/Router.php",
        "line": 302,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/var/www/html/nextcloud/lib/base.php",
        "line": 993,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/index.php",
        "line": 37,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/var/www/html/nextcloud/lib/private/Installer.php",
    "Line": 328,
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0",
  "version": "21.0.1.1"
}
```

This is on up-to-date CentOS Stream, mariadb 10.3.27, apache 2.4.37 and php 7.4.16.  Let me know if there's other information I can get that might be helpful.

Thanks,

**Comment by tayduivn** [comment]
> Fresh install of Nextcloud 21.0.1. Using directions at https://docs.nextcloud.com/server/21/admin_manual/installation/example_centos.html
> I don't have an apps/social/... directory.
> Command and output (run as webserver user):
> 
> ```
> bash-4.4$ ./occ app:enable social
> Could not extract app social: Out-of-path file extraction > ```
> 
> This is on up-to-date CentOS Stream, mariadb 10.3.27, apache 2.4.37 and php 7.4.16. Let me know if there's other information I can get that might be helpful.
> 
> Thanks,

> cd apps
> wget https://github.com/nextcloud/social/releases/download/v0.4.2/social-0.4.2.tar.gz
> tar -xf apps/social-0.4.2.tar.gz
> cd ..
> php occ app:enable social
> ```


> Open files in apps/social/lib/Migration then replace data type start with Type:: to corresponding data type in database system.
> Example I use mysql, so I replace Type::SMALLINT to 'smallint' and then enable the app

**Comment by Alexix78** [comment]
> Open files in apps/social/lib/Migration then replace data type start with Type:: to corresponding data type in database system.
> Example I use mysql, so I replace Type::SMALLINT to 'smallint' and then enable the app

Hi, can you please provide screen shots or be more specific how to do that, or copy the file and post it here.
I`m a newbiee and I caught my ears in this. Thank you

**Comment by tayduivn** [comment]
> > Open files in apps/social/lib/Migration then replace data type start with Type:: to corresponding data type in database system.
> > Example I use mysql, so I replace Type::SMALLINT to 'smallint' and then enable the app
> 
> Hi, can you please provide screen shots or be more specific how to do that, or copy the file and post it here.
> I`m a newbiee and I caught my ears in this. Thank you
I  uses mysql
[social.zip](https://github.com/nextcloud/social/files/6291895/social.zip)

**Comment by Alexix78** [comment]
> > > Open files in apps/social/lib/Migration then replace data type start with Type:: to corresponding data type in database system.
> > > Example I use mysql, so I replace Type::SMALLINT to 'smallint' and then enable the app
> > 
> > 
> > Hi, can you please provide screen shots or be more specific how to do that, or copy the file and post it here.
> > I`m a newbiee and I caught my ears in this. Thank you
> > I  uses mysql
> > [social.zip](https://github.com/nextcloud/social/files/6291895/social.zip)

thank you, but folder "lib" is empty that for folder with the important files aka migrate is missing too.
Please share, thank you!

**Comment by Alexix78** [comment]
> > > Open files in apps/social/lib/Migration then replace data type start with Type:: to corresponding data type in database system.
> > > Example I use mysql, so I replace Type::SMALLINT to 'smallint' and then enable the app
> > 
> > 
> > Hi, can you please provide screen shots or be more specific how to do that, or copy the file and post it here.
> > I`m a newbiee and I caught my ears in this. Thank you
> > I  uses mysql
> > [social.zip](https://github.com/nextcloud/social/files/6291895/social.zip)

your zip arhive have empty folders and some of the folder are missing with all the files.

**Comment by tayduivn** [comment]
[social.zip](https://github.com/nextcloud/social/files/6294575/social.zip)

**Comment by Alexix78** [comment]
> [social.zip](https://github.com/nextcloud/social/files/6294575/social.zip)
[![Everything Is AWESOME](https://i.ibb.co/jWnJ86j/ali.png)](https://www.youtube.com/watch?v=1qNeGSJaQ9Q "Thank You")

**Comment by Alexix78** [comment]
> [social.zip](https://github.com/nextcloud/social/files/6294575/social.zip)

Thank you, Now please tell me how do you solve this:

".well-known/webfinger isn't properly set up!
Social needs the .well-known automatic discovery to be properly set up. If Nextcloud is not installed in the root of the domain, it is often the case that Nextcloud can't configure this automatically. To use Social, the admin of this Nextcloud instance needs to manually configure the .well-known"?

**Comment by daufinsyd** [comment]
Hello,
I have the same error. With nextcloud 20.0.8 it said that the package could be extracted.
I updated the 21.0.1 and now I also have this error:

~~~
Error: Could not extract app social: Out-of-path file extraction {/tmp/oc_tmp_NCSybc-folder/social/vendor/bin/parallel-lint --> ../jakub-onderka/php-parallel-lint/parallel-lint}
~~~

**Comment by apis-mirea** [comment]
I guess the matter is not resolved, this is very annoying, I need social just to eliminate those nextcloud 21 webfinger and nodeinfo errors

**Comment by not-mms** [comment]
\+

**Comment by philliml74** [comment]
Again on a fresh install of NC21, received same error while attempting to install via UI and occ.  This is on Debian 10/PHP 7.4.  Even tried deploying the social app manually:

`:~/nextcloud$ php occ app:enable social
An unhandled exception has been thrown:
Error: Undefined constant Doctrine\DBAL\Types\Type::TEXT in /var/www/nextcloud/apps/social/lib/Migration/Version0003Date20200611000001.php:228
Stack trace:
#0 /var/www/nextcloud/apps/social/lib/Migration/Version0003Date20200611000001.php(76): OCA\Social\Migration\Version0003Date20200611000001->createActors()
#1 /var/www/nextcloud/lib/private/DB/MigrationService.php(455): OCA\Social\Migration\Version0003Date20200611000001->changeSchema()
#2 /var/www/nextcloud/lib/private/DB/MigrationService.php(418): OC\DB\MigrationService->migrateSchemaOnly()
#3 /var/www/nextcloud/lib/private/Installer.php(163): OC\DB\MigrationService->migrate()
#4 /var/www/nextcloud/core/Command/App/Enable.php(123): OC\Installer->installApp()
#5 /var/www/nextcloud/core/Command/App/Enable.php(93): OC\Core\Command\App\Enable->enableApp()
#6 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Enable->execute()
#7 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#8 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#10 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#11 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#12 /var/www/nextcloud/occ(11): require_once('...')
#13 {main}`

**Comment by philliml74** [comment]
> Again on a fresh install of NC21, received same error while attempting to install via UI and occ. This is on Debian 10/PHP 7.4. Even tried deploying the social app manually:
> 
> ```
> ~/nextcloud$ php occ app:enable social
> An unhandled exception has been thrown:
> Error: Undefined constant Doctrine\DBAL\Types\Type::TEXT in /var/www/nextcloud/apps/social/lib/Migration/Version0003Date20200611000001.php:228
> Stack trace:
> #0 /var/www/nextcloud/apps/social/lib/Migration/Version0003Date20200611000001.php(76): OCA\Social\Migration\Version0003Date20200611000001->createActors()
> #1 /var/www/nextcloud/lib/private/DB/MigrationService.php(455): OCA\Social\Migration\Version0003Date20200611000001->changeSchema()
> #2 /var/www/nextcloud/lib/private/DB/MigrationService.php(418): OC\DB\MigrationService->migrateSchemaOnly()
> #3 /var/www/nextcloud/lib/private/Installer.php(163): OC\DB\MigrationService->migrate()
> #4 /var/www/nextcloud/core/Command/App/Enable.php(123): OC\Installer->installApp()
> #5 /var/www/nextcloud/core/Command/App/Enable.php(93): OC\Core\Command\App\Enable->enableApp()
> #6 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Enable->execute()
> #7 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
> #8 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
> #9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
> #10 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
> #11 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
> #12 /var/www/nextcloud/occ(11): require_once('...')
> #13 {main}
> ```

I also attempted to perform a dev install using the instructions at https://github.com/nextcloud/social#development-setup and encountered the same issues again when attempting to enable the social app:

```~/nextcloud$ ./occ app:enable social
An unhandled exception has been thrown:
Error: Undefined constant Doctrine\DBAL\Types\Type::TEXT in /var/www/nextcloud/apps/social/lib/Migration/Version0003Date20200611000001.php:228
Stack trace:
#0 /var/www/nextcloud/apps/social/lib/Migration/Version0003Date20200611000001.php(76): OCA\Social\Migration\Version0003Date20200611000001->createActors()
#1 /var/www/nextcloud/lib/private/DB/MigrationService.php(455): OCA\Social\Migration\Version0003Date20200611000001->changeSchema()
#2 /var/www/nextcloud/lib/private/DB/MigrationService.php(418): OC\DB\MigrationService->migrateSchemaOnly()
#3 /var/www/nextcloud/lib/private/Installer.php(163): OC\DB\MigrationService->migrate()
#4 /var/www/nextcloud/core/Command/App/Enable.php(123): OC\Installer->installApp()
#5 /var/www/nextcloud/core/Command/App/Enable.php(93): OC\Core\Command\App\Enable->enableApp()
#6 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Enable->execute()
#7 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#8 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#10 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#11 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#12 /var/www/nextcloud/occ(11): require_once('...')
#13 {main}```

**Comment by Alexix78** [comment]
it is clear this app have a lot of bugs 
[https://github.com/nextcloud/social/issues](url)

**Comment by Megachip** [comment]
> Hi. I had same error too on Nextcloud 20.0.7 git. I avoided this error by following manual install.
> 
> ```
> cd apps
> wget https://github.com/nextcloud/social/releases/download/v0.4.2/social-0.4.2.tar.gz
> tar -xf apps/social-0.4.2.tar.gz
> cd ..
> php occ app:enable social
> ```

there is an apps/ to much in untar ;)

**Comment by Megachip** [comment]
> apps/social/lib/Migration

Can you provide a patch?

**Comment by Megachip** [comment]
> Open files in apps/social/lib/Migration then replace data type start with Type:: to corresponding data type in database system.
> Example I use mysql, so I replace Type::SMALLINT to 'smallint' and then enable the app

Can you provide a patch?

**Comment by Megachip** [comment]
> > Open files in apps/social/lib/Migration then replace data type start with Type:: to corresponding data type in database system.
> > Example I use mysql, so I replace Type::SMALLINT to 'smallint' and then enable the app
> 
> Can you provide a patch?

Looks like its already fixed in #1249

**Comment by derwotograf** [comment]
I am experiencing the same issue. 

error log file attached:
[error-log-social-app-nc.txt](https://github.com/nextcloud/social/files/6511902/error-log-social-app-nc.txt)

its on a webhosted instance from hoster netcup. on the system page of nc 20.0.9 it says the OS is Linux 4.9.0-12-amd64 x86_64. 

php
Version: 7.4.18
Memory Limit: 512 MB
Max Execution Time: 3600
Upload max size: 128 MB

database
Type: mysql
Version: 5.7.33
Size: 11,7 MB

not sure though if it is really an app issue. I am not really a system admin. the whole installation is just for private use.

**Comment by philliml74** [comment]
I can confirm that #1249 does appear to fix the issue.  I was able to pull and apply a patch file and enable the app.

The process that I followed:

1. Download the .zip file from the store page: https://apps.nextcloud.com/apps/social.  The specific link I .zip I pulled was https://github.com/nextcloud/social/releases/download/v0.4.2/social-0.4.2.tar.gz
2. Extract and place the social directory into the nextcloud/apps directory.
3. cd into the nextcloud/apps/social directory
4. Download the patch file from Github: https://patch-diff.githubusercontent.com/raw/nextcloud/social/pull/1249.patch
5. Run the following command to patch the files:
`git apply < 1249.patch`
6. Install the app manually with the occ command:
`./occ app:enable social`

I hope that helps someone who just can't wait for the commit.

**Comment by derwotograf** [comment]
Thanks @philliml74 for your answer. I could also solve this by manually downloading the app and then extract it into the apps folder. As my ssh knowledge is pretty zero, I could handle everything with the ftp client, webhoster file app within plesk and nextcloud webinterface.

**Comment by Danie10** [comment]
What a mess... I've had teh same issue for months and my Social app has just been broken. The solution above worked for me for extracting and updating the app. Then I had the same as many have had with the webfinger error (why when all I did was run updates to NextCloud and run the app updates from within NextCloud when needed???).

I compared an offline backup from many months back for .htaccess when it all still worked, and noticed the lines below were removed (clearly from one of the updates). Interesting these lines back removed the webfinger error but trying to post an update just says "failed to create post". Really frustrating, as these updates (and .htaccess changes) should be tested.

```
  RewriteRule ^\.well-known/host-meta /public.php?service=host-meta [QSA,L]
  RewriteRule ^\.well-known/host-meta\.json /public.php?service=host-meta-json [QSA,L]
  RewriteRule ^\.well-known/webfinger /public.php?service=webfinger [QSA,L]
  RewriteRule ^\.well-known/nodeinfo /public.php?service=nodeinfo [QSA,L]
```

**Comment by Danie10** [comment]
Error I'm getting now from logs when I try to post a Social post is:

```

Error | PHP | Error: Array to string conversion at /home/soft/public_html/nextcloud/apps/social/lib/Model/ActivityPub/ACore.php#569<<closure>>OC\Log\ErrorHandler::onError(8, "Array to string conversion", "/home/soft/ ... p", 569, { as: 8,valu ... e})/home/soft/public_html/nextcloud/apps/social/lib/Model/ActivityPub/ACore.php - line 569: strip_tags("<p><span cl ... >", [ "a","p","span","br"])/home/soft/public_html/nextcloud/apps/social/lib/Model/ActivityPub/ACore.php - line 498: OCA\Social\Model\ActivityPub\ACore->validateEntryString(8, "<p><span cl ... >")/home/soft/public_html/nextcloud/apps/social/lib/Model/ActivityPub/Stream.php - line 428: OCA\Social\Model\ActivityPub\ACore->validate(8, "content", { 0: "And 42 ... "}, "")/home/soft/public_html/nextcloud/apps/social/lib/Model/ActivityPub/Object/Note.php - line 185: OCA\Social\Model\ActivityPub\Stream->importFromDatabase({ 0: "And 42 ... "})/home/soft/public_html/nextcloud/apps/social/lib/Db/StreamRequestBuilder.php - line 211: OCA\Social\Model\ActivityPub\Object\Note->importFromDatabase({ 0: "And 42 ... "})/home/soft/public_html/nextcloud/apps/social/vendor/daita/my-small-php-tools/lib/Db/ExtendedQueryBuilder.php - line 538: OCA\Social\Db\StreamRequestBuilder->parseStreamSelectSql({ 0: "And 42 ... "}, OCA\Social\D ... {})/home/soft/public_html/nextcloud/apps/social/lib/Db/StreamRequestBuilder.php - line 192: daita\MySmallPhpTools\Db\ExtendedQueryBuilder->getRows([ OCA\Social ... "])/home/soft/public_html/nextcloud/apps/social/lib/Db/StreamRequest.php - line 432: OCA\Social\Db\StreamRequestBuilder->getStreamsFromRequest(OCA\Social\D ... {})/home/soft/public_html/nextcloud/apps/social/lib/Service/StreamService.php - line 417: OCA\Social\Db\StreamRequest->getTimelineHome_dep(1625399608, 25, 1)/home/soft/public_html/nextcloud/apps/social/lib/Controller/LocalController.php - line 382: OCA\Social\Service\StreamService->getStreamHome(1625399608, 25)/home/soft/public_html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218: OCA\Social\Controller\LocalController->streamHome(1625399608, 25)/home/soft/public_html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127: OC\AppFramework\Http\Dispatcher->executeController(OCA\Social\C ... {}, "streamHome")/home/soft/public_html/nextcloud/lib/private/AppFramework/App.php - line 157: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Social\C ... {}, "streamHome")/home/soft/public_html/nextcloud/lib/private/Route/Router.php - line 302: OC\AppFramework\App::main("OCA\\Social ... r", "streamHome", OC\AppFramew ... {}, { _route: "s ... "})/home/soft/public_html/nextcloud/lib/base.php - line 993: OC\Route\Router->match("/apps/socia ... e")/home/soft/public_html/nextcloud/index.php - line 37: OC::handleRequest()
-- | -- | --

```

**Comment by Danie10** [comment]
Out of frustration yesterday I deleted and removed my entire Nextcloud installation and removed the the old directories. I did a clean Nextcloud installation and then when I tried to do the download and install from inside the Nextcloud apps area I get:

`Could not extract app social: Out-of-path file extraction {/tmp/oc_tmp_AccEa3-folder/social/vendor/bin/parallel-lint --> ../jakub-onderka/php-parallel-lint/parallel-lint}`

What I just don't understand is the first time I tried using this app in early 2020 or late 2019 (forget exact date) it installed just fine. It needed no manual intervention, and I'm not sideloading some alpha version of it. What broke at the end of 2020 as I see mine has been offline for just over 6 months (it never updated)? Is it perhaps that the install version in the Nextcloud apps is broken or out of date? It shows in Nextcloud as version 0.4.2

**Comment by Mecallie** [comment]
I know this is not really the right place for it, but filing a bug or feature request did not seem the proper way either.

Is there any way I can help bring this integration back to life? I am willing to spend some money on a working social app from within Nextcloud. Unfortunately I am not a coder so I cannot really help with that. I am an IT specialist though, so might be able to help with testing.

If anyone knows a proper way to get this project on rails again please let me know!

**Comment by mortee** [comment]
+1, like 1,5 years later?

**Comment by Danie10** [comment]
@ArtificialOwl appears to be the maintainer, so can maybe advise, as I don't see any new releases for this integration for a while.

**Comment by Danie10** [comment]
OK thanks will look - I'd been watching here for the last year for any fixes but it only showed v0.4.2 as the last release, so did not realise there were newer releases.

**Comment by Danie10** [comment]
I enabled it, and when clicking download it just gives the error "An error occurred during the request. Unable to proceed." So not sure if it should be manually installed, but then need a link to the 0.6.0-rc1 zip file.

**Comment by ArtificialOwl** [comment]
For security reason, we now use a different repository for the releases of our apps: https://github.com/nextcloud-releases/social/

**Comment by Danie10** [comment]
OK thanks sorted with download. It gave same error, so I deleted my old sub-folder, and then it installed fine. So, seems the issue with the original update may have also related to something to do with the old setup that changed. It starts up now though fine.

**Comment by SchBenedikt** [comment]
Automatically closed — the app has a standard Nextcloud app structure with proper `appinfo/info.xml`, `composer.json`, and `vendor/autoload.php`. No extraction issues are present.
