### ISSUE TITLE
Exception when calling social:reset or social:check:install

### ISSUE THREAD

**Issue by sledz** [nextcloud/social#1404]
**Describe the bug**
When calling a **social:reset** or a **social:check:install** the same unhandled exception is thrown.

```
TypeError: Return value of "OCA\Social\Command\CheckInstall::execute()" must be of the type int, "null" returned. in /srv/www/htdocs/nextcloud/apps/emlviewer/vendor/symfony/console/Command/Command.php:261
Stack trace:
#0 /srv/www/htdocs/nextcloud/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run()
#1 /srv/www/htdocs/nextcloud/apps/emlviewer/vendor/symfony/console/Application.php(911): OC\Core\Command\Base->run()
#2 /srv/www/htdocs/nextcloud/apps/emlviewer/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand()
#3 /srv/www/htdocs/nextcloud/apps/emlviewer/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun()
#4 /srv/www/htdocs/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#5 /srv/www/htdocs/nextcloud/console.php(99): OC\Console\Application->run()
#6 /srv/www/htdocs/nextcloud/occ(11): require_once('/srv/www/htdocs...')
```

```
TypeError: Return value of "OCA\Social\Command\Reset::execute()" must be of the type int, "null" returned. in /srv/www/htdocs/nextcloud/apps/emlviewer/vendor/symfony/console/Command/Command.php:261
Stack trace:
#0 /srv/www/htdocs/nextcloud/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run()
#1 /srv/www/htdocs/nextcloud/apps/emlviewer/vendor/symfony/console/Application.php(911): OC\Core\Command\Base->run()
#2 /srv/www/htdocs/nextcloud/apps/emlviewer/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand()
#3 /srv/www/htdocs/nextcloud/apps/emlviewer/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun()
#4 /srv/www/htdocs/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#5 /srv/www/htdocs/nextcloud/console.php(99): OC\Console\Application->run()
#6 /srv/www/htdocs/nextcloud/occ(11): require_once('/srv/www/htdocs...')
```

None of the hints from #1129 and #1161 led to a solution of the problem. 🙁

**To Reproduce**
1. Call `occ social:check:install` or `occ social:reset`

**Expected behavior**
No exception.

**Client details:**
No client involved.

<details>
<summary>Server details</summary>

**Social app version:**
0.4.2

**Operating system**:
openSUSE Leap 15.3

**Web server:**
Name        : apache2
Version     : 2.4.43
Release     : 3.32.1
Architecture: x86_64

**Database:**
Name        : mariadb
Version     : 10.5.12
Release     : 3.9.1
Architecture: x86_64

**PHP version:**
Name        : php7
Version     : 7.4.26
Release     : 342.1
Architecture: x86_64

**Nextcloud version:** (see Nextcloud admin page)
Name        : nextcloud
Version     : 23.0.4
Release     : lp153.158.1
Architecture: noarch

</details>

**Comment by SchBenedikt** [comment]
Automatically closed — `social:reset` command now exists in `Command/Reset.php` with `--uninstall` option and is properly registered in `appinfo/info.xml`.
