### ISSUE TITLE
Failed to enable 0.5.0 due to missing autoload.php

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/social#1519]
I've been running into this when trying to enable th app on my personal instance. Seems like the autoloader is missing from the release archive.

Also when updating from the web UI the instance will be stuck in maintenance mode.

FYI @CarlSchwan @ArtificialOwl 

```
An unhandled exception has been thrown:
Error: Failed opening required '/var/www/nextcloud/apps-extra/social/lib/AppInfo/../../vendor/autoload.php' (include_path='/var/www/nextcloud/apps-extra/news/vendor/pear/net_url2:/var/www/nextcloud/3rdparty/pear/archive_tar:/var/www/nextcloud/3rdparty/pear/console_getopt:/var/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/var/www/nextcloud/3rdparty/pear/pear_exception:/var/www/nextcloud/apps:/var/www/nextcloud/apps-extra') in /var/www/nextcloud/apps-extra/social/lib/AppInfo/Application.php:54
Stack trace:
#0 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(571): include()
#1 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php(207): class_exists()
#4 /var/www/nextcloud/lib/private/legacy/OC_App.php(173): OC\AppFramework\Bootstrap\Coordinator->isBootable()
#5 /var/www/nextcloud/lib/private/legacy/OC_App.php(1049): OC_App::loadApp()
#6 /var/www/nextcloud/lib/private/Installer.php(156): OC_App::executeRepairSteps()
#7 /var/www/nextcloud/core/Command/App/Enable.php(111): OC\Installer->installApp()
#8 /var/www/nextcloud/core/Command/App/Enable.php(81): OC\Core\Command\App\Enable->enableApp()
#9 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Enable->execute()
#10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#11 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#12 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#13 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#14 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#15 /var/www/nextcloud/occ(11): require_once('...')
```

**Comment by miklobit** [comment]
related to https://github.com/nextcloud/social/issues/1505#issuecomment-1304820285

**Comment by ArtificialOwl** [comment]
please test last version from appstore
