### ISSUE TITLE
Unable to post or view the post

### ISSUE THREAD

**Issue by srijansaxena11** [nextcloud/social#1700]
**Describe the bug**
I set up the social app and tried posting. It does not give any error message while posting but all the posts shown below are empty with just my profile picture showing and nothing else. I am not sure if posts are not getting posted or are they just not displaying.

**To Reproduce**
1. Go to social app
2. Write something and click on Post to followers

**Expected behavior**
Post should be posted and visible in the timeline below.

But the post is not visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/34964694/227514587-dcf4911b-bf63-4e9e-87f8-b80a3a1c66c9.png)

**Client details:**
 - OS: Windows
 - Browser: Microsoft Edge
 - Version 11
 - Device: Desktop

<details>
<summary>Server details</summary>

**Social app version:** 0.6.0-beta5

**Operating system**: Ubuntu 22.04.1 LTS

**Web server:** Apache

**Database:** MySQL

**PHP version:** 8.1.2

**Nextcloud version:** (see Nextcloud admin page) 26.0.0

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
vue.runtime.esm.js:3049 
        
       TypeError: Cannot read properties of undefined (reading 'acct')
    at i (TimelinePost.vue?9195:3:2390)
    at e._render (vue.runtime.esm.js:2684:28)
    at i.r (vue.runtime.esm.js:3875:27)
    at e.get (vue.runtime.esm.js:3446:33)
    at new e (vue.runtime.esm.js:3436:51)
    at e (vue.runtime.esm.js:3892:5)
    at Qn.$mount (vue.runtime.esm.js:8772:12)
    at init (vue.runtime.esm.js:4407:19)
    at vue.runtime.esm.js:6567:17
    at d (vue.runtime.esm.js:6521:13)
```

</details>

**Comment by roelfrenkema** [comment]
something like POST /apps/social/inbox HTTP/1.1" 500 6264

**Comment by srijansaxena11** [comment]
> something like POST /apps/social/inbox HTTP/1.1" 500 6264

What do you mean?

**Comment by srijansaxena11** [comment]
> something like POST /apps/social/inbox HTTP/1.1" 500 6264

What do you mean?

**Comment by srijansaxena11** [comment]
> something like POST /apps/social/inbox HTTP/1.1" 500 6264

What do you mean?

**Comment by roelfrenkema** [comment]
Hmmm I tried posting a note through occ but it always quits with the message 'The "userid" argument does not exist'. I wonder if thats related.

**Comment by srijansaxena11** [comment]
> Hmmm I tried posting a note through occ but it always quits with the message 'The "userid" argument does not exist'. I wonder if thats related.

Post works fine now after the last update

**Comment by roelfrenkema** [comment]
Nope not here.

**Comment by srijansaxena11** [comment]
> 

uhm? what is not there?

**Comment by roelfrenkema** [comment]
Messages dont go out. I only receive global timeline. Cant see profiles clicking on people I follow either.

**Comment by srijansaxena11** [comment]
> Messages dont go out. I only receive global timeline. Cant see profiles clicking on people I follow either.

By messages you mean posts? Profiles don't work for me either. Not even my own profile opens up. How do you see global timeline? Help me to set it up.

**Comment by ArtificialOwl** [comment]
can you replicate the issue after installing https://github.com/nextcloud-releases/social/releases/download/v0.6.0-rc1/social-v0.6.0-rc1.tar.gz ?

**Comment by srijansaxena11** [comment]
> can you replicate the issue after installing https://github.com/nextcloud-releases/social/releases/download/v0.6.0-rc1/social-v0.6.0-rc1.tar.gz ?

This is working fine now with rc1. Thank you. Closing it hereby.
