### ISSUE TITLE
The social app is not working correctly 

### ISSUE THREAD

**Issue by SchBenedikt** [nextcloud/social#1876]
**Describe the bug**
We have installed the Social app on our Nextcloud instance. You can post messages and also see the messages yourself. The only thing that doesn’t work is the profile tab where the profile should be displayed. There’s just a loading icon here.
What could be the reason?

**Expected behavior**
A loading symbol is only displayed for the "Profile" field; sometimes nothing at all.

**Screenshots**
![image](https://github.com/nextcloud/social/assets/137323528/f368fe7d-1874-48e5-804c-3e5e23e13e9a)

**Client details:**
 - App-Version: 0.6.1
 - NC-Version: 28.0.1

**Comment by joshtrichards** [comment]
- Any output in you browser console when this happens?
- Also anything interesting in the browser console network tab?

**Comment by SchBenedikt** [comment]
Nothing strange appears in the browser console in Network Tab. I have attached the log from the console here again.
[nc-log.log](https://github.com/nextcloud/social/files/13919352/nc-log.log)

**Comment by SergSel2006** [comment]
I have the same problem But with different Nextcloud version `27.1.5`, but app version is the same.
Logs are familiar with the author logs.
[console-export-2024-1-20_21-27-26.txt](https://github.com/nextcloud/social/files/13998229/console-export-2024-1-20_21-27-26.txt)

**Comment by SergSel2006** [comment]
For some reason this issue disappears after an app reset.
Looks like there's no implemented way of migration from legacy data.

**Comment by SchBenedikt** [comment]
I tried that too; I also tried to install another version, but unfortunately it didn't work.

**Comment by chenasraf** [comment]
I'm getting an error trying to load any profile, in the dev console:

```
TypeError: Cannot read properties of undefined (reading 'acct')
    at i.<anonymous> (Profile.vue:1:390)
    at e._render (vue.runtime.esm.js:2684:28)
    at i.r (vue.runtime.esm.js:3875:27)
    at e.get (vue.runtime.esm.js:3446:33)
    at e.run (vue.runtime.esm.js:3522:30)
    at kr (vue.runtime.esm.js:4121:17)
    at Array.<anonymous> (vue.runtime.esm.js:3143:20)
    at _n (vue.runtime.esm.js:3065:16)
```

Which points to this file:

```vue
var render = function render(){var _vm=this,_c=_vm._self._c;return _c('div',{staticClass:"social__wrapper",class:{'icon-loading': !_vm.accountLoaded}},[(_vm.accountLoaded && _vm.accountInfo)?_c('ProfileInfo',{attrs:{"uid":_vm.uid}}):_vm._e(),_vm._v(" "),(_vm.accountInfo && _vm.$route.name === 'profile')?_c('Composer',{attrs:{"initial-mention":_vm.accountInfo.acct === _vm.currentAccount.acct ? null : _vm.accountInfo,"default-visibility":"direct"}}):_vm._e(),_vm._v(" "),(_vm.accountLoaded && _vm.accountInfo && _vm.isLocal)?_c('router-view',{attrs:{"name":"details"}}):_vm._e(),_vm._v(" "),(_vm.accountLoaded && !_vm.accountInfo)?_c('NcEmptyContent',{attrs:{"title":_vm.t('social', 'User not found'),"description":_vm.t('social', 'Sorry, we could not find the account of {userId}', { userId: _vm.uid })},scopedSlots:_vm._u([{key:"icon",fn:function(){return [_c('img',{staticClass:"icon-illustration",attrs:{"src":_vm.emptyContentImage,"alt":""}})]},proxy:true}],null,false,2365308424)}):_vm._e()],1)
}
var staticRenderFns = []

export { render, staticRenderFns }
```

Search for `_vm.currentAccount.acct ?`

**Comment by Blintmester** [comment]
I have the same issue with nc 28.0.2 (on TrueNAS SCALE), and social app 0.6.1.
When I trying to follow NextCloud mastodon, I get the same error, as @chenasraf.
When trying to open profile I got this error:
```
TypeError: t.currentAccount is undefined
    R Profile.vue:1
    VueJS 26
    init vue-router.esm.js:3005
    init vue-router.esm.js:3004
    updateRoute vue-router.esm.js:2414
    transitionTo vue-router.esm.js:2263
    confirmTransition vue-router.esm.js:2402
    r vue-router.esm.js:2084
    r vue-router.esm.js:2091
    r vue-router.esm.js:2091
    r vue-router.esm.js:2091
    Rn vue-router.esm.js:2095
    confirmTransition vue-router.esm.js:2396
    r vue-router.esm.js:2084
    r vue-router.esm.js:2088
    h vue-router.esm.js:2384
    n vue-router.esm.js:2162
    h vue-router.esm.js:2362
    r vue-router.esm.js:2087
    r vue-router.esm.js:2091
    r vue-router.esm.js:2091
    r vue-router.esm.js:2091
    Rn vue-router.esm.js:2095
    confirmTransition vue-router.esm.js:2392
    transitionTo vue-router.esm.js:2260
    push vue-router.esm.js:2606
    push vue-router.esm.js:3039
    g vue-router.esm.js:1139
    onClick NcAppNavigationItem.js:2
    click NcAppNavigationItem.js:2
    VueJS 3
```

**Comment by SchBenedikt** [comment]
I solved some issues
#1993
