### ISSUE TITLE
Webfinger and following are not working

### ISSUE THREAD

**Issue by oculos** [nextcloud/social#1950]
Hi,

I just installed the social app, and I'm having two problems:

1 - Webfinger is failing

I am getting this error:

```
{"reqId":"uffrHTZlF7EMivwzGhJw","level":3,"time":"2024-11-21T14:48:55+00:00","remoteAddr":"10.10.20.30","user":"--","app":"index","method":"GET","url":"/index.php/.well-known/webfinger","message":"parse_str(): Argument #1 ($string) must be of type string, null given in file '/var/www/nextcloud/apps/social/lib/WellKnown/WebfingerHandler.php' line 219","userAgent":"curl/8.7.1","version":"30.0.2.2","exception":{"Exception":"Exception","Message":"parse_str(): Argument #1 ($string) must be of type string, null given in file '/var/www/nextcloud/apps/social/lib/WellKnown/WebfingerHandler.php' line 219","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1001,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":146,"Previous":{"Exception":"TypeError","Message":"parse_str(): Argument #1 ($string) must be of type string, null given","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/social/lib/WellKnown/WebfingerHandler.php","line":219,"function":"parse_str"},{"file":"/var/www/nextcloud/apps/social/lib/WellKnown/WebfingerHandler.php","line":99,"function":"getSubjectFromRequest","class":"OCA\\Social\\WellKnown\\WebfingerHandler","type":"->"},{"file":"/var/www/nextcloud/apps/social/lib/WellKnown/WebfingerHandler.php","line":71,"function":"handleWebfinger","class":"OCA\\Social\\WellKnown\\WebfingerHandler","type":"->"},{"file":"/var/www/nextcloud/lib/private/Http/WellKnown/RequestManager.php","line":60,"function":"handle","class":"OCA\\Social\\WellKnown\\WebfingerHandler","type":"->"},{"function":"OC\\Http\\WellKnown\\{closure}","class":"OC\\Http\\WellKnown\\RequestManager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Http/WellKnown/RequestManager.php","line":61,"function":"array_reduce"},{"file":"/var/www/nextcloud/core/Controller/WellKnownController.php","line":40,"function":"process","class":"OC\\Http\\WellKnown\\RequestManager","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":208,"function":"handle","class":"OC\\Core\\Controller\\WellKnownController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":114,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1001,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/social/lib/WellKnown/WebfingerHandler.php","Line":219},"message":"parse_str(): Argument #1 ($string) must be of type string, null given in file '/var/www/nextcloud/apps/social/lib/WellKnown/WebfingerHandler.php' line 219","exception":{},"CustomMessage":"parse_str(): Argument #1 ($string) must be of type string, null given in file '/var/www/nextcloud/apps/social/lib/WellKnown/WebfingerHandler.php' line 219"}}

```

2 - Following someone, like Nextcloud, fails:

```
{"reqId":"YnWTapG51cYJ4f9g2DGp","level":3,"time":"2024-11-21T14:48:39+00:00","remoteAddr":"1010.30.20","user":"francis","app":"core","method":"GET","url":"/index.php/apps/social/api/v1/timelines/direct?account=francis&min_id=1732200412380175&limit=15","message":"More than 30 characters for an output column name are not allowed on Oracle.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15","version":"30.0.2.2","exception":{"Exception":"Doctrine\\DBAL\\Query\\QueryException","Message":"More than 30 characters for an output column name are not allowed on Oracle.","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":284,"function":"prepareForExecute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":266,"function":"executeQuery","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/social/lib/Tools/Db/ExtendedQueryBuilder.php","line":494,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/social/lib/Db/StreamRequestBuilder.php","line":168,"function":"getRows","class":"OCA\\Social\\Tools\\Db\\ExtendedQueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/social/lib/Db/StreamRequest.php","line":475,"function":"getStreamsFromRequest","class":"OCA\\Social\\Db\\StreamRequestBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/social/lib/Db/StreamRequest.php","line":401,"function":"getTimelineDirect","class":"OCA\\Social\\Db\\StreamRequest","type":"->"},{"file":"/var/www/nextcloud/apps/social/lib/Service/StreamService.php","line":417,"function":"getTimeline","class":"OCA\\Social\\Db\\StreamRequest","type":"->"},{"file":"/var/www/nextcloud/apps/social/lib/Controller/ApiController.php","line":431,"function":"getTimeline","class":"OCA\\Social\\Service\\StreamService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":208,"function":"timelines","class":"OCA\\Social\\Controller\\ApiController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":114,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1001,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","Line":217,"message":"More than 30 characters for an output column name are not allowed on Oracle.","query":"SELECT DISTINCT `s`.`id`, `s`.`nid`, `s`.`id_prim`, `s`.`visibility`, `s`.`type`, `s`.`subtype`, `s`.`to`, `s`.`to_array`, `s`.`cc`, `s`.`bcc`, `s`.`content`, `s`.`summary`, `s`.`published`, `s`.`published_time`, `s`.`attributed_to`, `s`.`attributed_to_prim`, `s`.`in_reply_to`, `s`.`in_reply_to_prim`, `s`.`activity_id`, `s`.`object_id`, `s`.`object_id_prim`, `s`.`hashtags`, `s`.`details`, `s`.`source`, `s`.`instances`, `s`.`attachments`, `s`.`cache`, `s`.`creation`, `s`.`local`, `s`.`filter_duplicate`, `ca`.`id` AS `cacheactor_id`, `ca`.`nid` AS `cacheactor_nid`, `ca`.`type` AS `cacheactor_type`, `ca`.`icon_id` AS `cacheactor_icon_id`, `ca`.`account` AS `cacheactor_account`, `ca`.`following` AS `cacheactor_following`, `ca`.`followers` AS `cacheactor_followers`, `ca`.`inbox` AS `cacheactor_inbox`, `ca`.`shared_inbox` AS `cacheactor_shared_inbox`, `ca`.`outbox` AS `cacheactor_outbox`, `ca`.`featured` AS `cacheactor_featured`, `ca`.`url` AS `cacheactor_url`, `ca`.`preferred_username` AS `cacheactor_preferred_username`, `ca`.`name` AS `cacheactor_name`, `ca`.`summary` AS `cacheactor_summary`, `ca`.`public_key` AS `cacheactor_public_key`, `ca`.`source` AS `cacheactor_source`, `ca`.`details` AS `cacheactor_details`, `ca`.`creation` AS `cacheactor_creation`, `ca`.`local` AS `cacheactor_local`, `cacd`.`id` AS `cacheactor_cachedocument_id`, `cacd`.`type` AS `cacheactor_cachedocument_type`, `cacd`.`mime_type` AS `cacheactor_cachedocument_mime_type`, `cacd`.`media_type` AS `cacheactor_cachedocument_media_type`, `cacd`.`url` AS `cacheactor_cachedocument_url`, `cacd`.`local_copy` AS `cacheactor_cachedocument_local_copy`, `cacd`.`resized_copy` AS `cacheactor_cachedocument_resized_copy`, `cacd`.`caching` AS `cacheactor_cachedocument_caching`, `cacd`.`public` AS `cacheactor_cachedocument_public`, `cacd`.`error` AS `cacheactor_cachedocument_error`, `cacd`.`creation` AS `cacheactor_cachedocument_creation` FROM `*PREFIX*social_stream` `s` INNER JOIN `*PREFIX*social_cache_actor` `ca` ON `ca`.`id_prim` = `s`.`attributed_to_prim` LEFT JOIN `*PREFIX*social_cache_doc` `cacd` ON `ca`.`icon_id` = `cacd`.`id_prim`, `*PREFIX*social_stream_dest` `sd` WHERE (`s`.`type` <> :dcValue1) AND (`s`.`nid` > :dcValue2) AND ((`sd`.`stream_id` = `s`.`id_prim`) AND (`sd`.`actor_id` = :dcValue3) AND (`sd`.`type` = :dcValue4)) ORDER BY `s`.`nid` asc LIMIT 15","columns":["cacheactor_cachedocument_mime_type","cacheactor_cachedocument_media_type","cacheactor_cachedocument_local_copy","cacheactor_cachedocument_resized_copy","cacheactor_cachedocument_caching","cacheactor_cachedocument_public","cacheactor_cachedocument_creation"],"exception":{},"CustomMessage":"More than 30 characters for an output column name are not allowed on Oracle."}}
``` 

I reset the app using occ social:reset, but the problem is still there.

Best,
Francis

**Comment by joshtrichards** [comment]
First item is a duplicate of #1888

**Comment by teledyn** [comment]
the 30 Char Issue persists in 30.0.2 and using Social 0.8.0

**Comment by noci2012** [comment]
It should only  be an error if someone is using oracle as a database...
otherwise there are different limits.

**Comment by Casuallynoted** [comment]
Also getting this error and am unable to use Social. Is there a way these queries can be fixed to work in the db?

**Comment by christiansass** [comment]
## Experiencing the same error on PostgreSQL (not Oracle)

Starting January 20, 2026, my logs show repeated errors:
```
QueryException: More than 30 characters for an output column name are not allowed on Oracle.
GET /apps/social/api/v1/timelines/home?account=[username]&limit=15
```

### Environment
- **Nextcloud:** Hub 10 (31.0.9)
- **Social app:** 0.7.0
- **Database:** PostgreSQL 17.6 (NOT Oracle)
- **OS:** Linux 6.1.0-41-amd64 x86_64
- **PHP:** 8.3.25

### The Issue

The strange part: I'm running **PostgreSQL**, which doesn't have Oracle's 30-character column name limitation. This suggests either:

1. The database type detection is incorrectly identifying PostgreSQL as Oracle, or
2. The Oracle compatibility check is being triggered incorrectly

The errors flooded the logs continuously (1745+ errors since January 14). I've temporarily disabled the Social app, which stopped the errors completely—confirming Social as the source.

### Note

I'm not a developer—I worked with Claude (Anthropic's AI) to help analyze these logs and draft this report. The PostgreSQL/Oracle discrepancy was identified during our troubleshooting session.

Happy to provide additional debugging information if helpful.

**Comment by teledyn** [comment]
Social is very broken and should be removed. A year or so ago someone on
Fediverse was hoping to code a replacement but I haven't heard from them
since. Social was fun when it kind of partially worked back in nc-20

Gary Lawrence Murphy - Toronto CA - Fediverse ***@***.***> -
Tumblr <https://teledyn.tumblr.com> - Blog <https://blog.teledyn.com> - Home
<https://www.teledyn.com/>

**Comment by SchBenedikt** [comment]
Hi @teledyn, @christiansass, @Casuallynoted, ...

I've tried to fix the bugs in the app – at least the basic functions (including the profile page) should be working again, but the application is still very buggy.

Perhaps you could give it a try?


More infos:
https://github.com/nextcloud/social/issues/1993
https://help.nextcloud.com/t/nextcloud-social-fediverse-is-finally-working-again/238472
https://github.com/SchBenedikt/social

**Comment by teledyn** [comment]
Oh, a fix could be fun! What is the version number of your update? I was
unable to get anything useful from the 0.7.0 in the catalog and it is now
marked untested. Only the feed worked, very slowly.

Gary Lawrence Murphy - Toronto CA - Fediverse ***@***.***> -
Tumblr <https://teledyn.tumblr.com> - Blog <https://blog.teledyn.com> - Home
<https://www.teledyn.com/>

**Comment by teledyn** [comment]
https://github.com/SchBenedikt/social

I should have clicked first 🤣

Gary Lawrence Murphy - Toronto CA - Fediverse ***@***.***> -
Tumblr <https://teledyn.tumblr.com> - Blog <https://blog.teledyn.com> - Home
<https://www.teledyn.com/>

**Comment by christiansass** [comment]
I just want to let you guys know that I am really thankful that you are still trying to keep this thing alive. I do think that decentralizing social media is a worthy task and wondering how this app can contribute to that cause is something I am going to keep tabs on. I did go check the app market on my Next Cloud installation and didn't see an update yet so I will be watching for that

**Comment by SchBenedikt** [comment]
Hi @christiansass,
check out https://github.com/nextcloud/social/issues/1993 and my own repository https://github.com/schBenedikt/social!
That one should work again!

**Comment by christiansass** [comment]
good to know, I’ll make sure to check it out next time I get back into my studio

**Comment by SchBenedikt** [comment]
@christiansass The new app now also is on https://apps.nextcloud.com/apps/social!

**Comment by noci2012** [comment]
It still happens in 0.10
```
QueryExceptionMore than 30 characters for an output column name are not allowed on Oracle.

    /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.phpLine 256

    OC\DB\QueryBuilder\QueryBuilder->prepareForExecute()

    /var/www/nextcloud/apps/social/lib/Tools/Db/ExtendedQueryBuilder.phpLine 491

    OC\DB\QueryBuilder\QueryBuilder->executeQuery()

    /var/www/nextcloud/apps/social/lib/Db/StreamRequestBuilder.phpLine 167

    OCA\Social\Tools\Db\ExtendedQueryBuilder->getRows()

    /var/www/nextcloud/apps/social/lib/Db/StreamRequest.phpLine 527

    OCA\Social\Db\StreamRequestBuilder->getStreamsFromRequest()

    /var/www/nextcloud/apps/social/lib/Db/StreamRequest.phpLine 413

    OCA\Social\Db\StreamRequest->getTimelineAccount()

    /var/www/nextcloud/apps/social/lib/Service/StreamService.phpLine 440

    OCA\Social\Db\StreamRequest->getTimeline()

    /var/www/nextcloud/apps/social/lib/Controller/ApiController.phpLine 638

    OCA\Social\Service\StreamService->getTimeline()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.phpLine 165

    OCA\Social\Controller\ApiController->accountStatuses()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.phpLine 78

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/nextcloud/lib/private/AppFramework/App.phpLine 137

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.phpLine 324

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.phpLine 1159

    OC\Route\Router->match()

    /var/www/nextcloud/index.phpLine 25

    OC::handleRequest()

----
{
  "reqId": "T6lxtrlFQe3S7OCHHp8B",
  "level": 3,
  "time": "2026-07-03T13:59:32+02:00",
  "remoteAddr": "2a10:3781:286:777:26a8:8f47:b299:6f97",
  "user": "username",
  "app": "core",
  "method": "GET",
  "url": "/apps/social/api/v1/accounts/username/statuses?limit=15
  "scriptName": "/index.php",
  "message": "More than 30 characters for an output column name are not allowed on Oracle.",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:151.0) Gecko/20100101 Firefox/151.0",
  "version": "34.0.1.2",
  "exception": {
    "Exception": "Doctrine\\DBAL\\Query\\QueryException",
    "Message": "More than 30 characters for an output column name are not allowed on Oracle.",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php",
        "line": 256,
        "function": "prepareForExecute",
        "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/social/lib/Tools/Db/ExtendedQueryBuilder.php",
        "line": 491,
        "function": "executeQuery",
        "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/social/lib/Db/StreamRequestBuilder.php",
        "line": 167,
        "function": "getRows",
        "class": "OCA\\Social\\Tools\\Db\\ExtendedQueryBuilder",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/social/lib/Db/StreamRequest.php",
        "line": 527,
        "function": "getStreamsFromRequest",
        "class": "OCA\\Social\\Db\\StreamRequestBuilder",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/social/lib/Db/StreamRequest.php",
        "line": 413,
        "function": "getTimelineAccount",
        "class": "OCA\\Social\\Db\\StreamRequest",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/social/lib/Service/StreamService.php",
        "line": 440,
        "function": "getTimeline",
        "class": "OCA\\Social\\Db\\StreamRequest",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/social/lib/Controller/ApiController.php",
        "line": 638,
        "function": "getTimeline",
        "class": "OCA\\Social\\Service\\StreamService",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 165,
        "function": "accountStatuses",
        "class": "OCA\\Social\\Controller\\ApiController",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 78,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
        "line": 137,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Route/Router.php",
        "line": 324,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/var/www/nextcloud/lib/base.php",
        "line": 1159,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/index.php",
        "line": 25,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php",
    "Line": 212,
    "message": "More than 30 characters for an output column name are not allowed on Oracle.",
    "query": "SELECT DISTINCT `s`.`id`, `s`.`nid`, `s`.`id_prim`, `s`.`visibility`, `s`.`type`, `s`.`subtype`, `s`.`to`, `s`.`to_array`, `s`.`cc`, `s`.`bcc`, `s`.`content`, `s`.`summary`, `s`.`published`, `s`.`published_time`, `s`.`attributed_to`, `s`.`attributed_to_prim`, `s`.`in_reply_to`, `s`.`in_reply_to_prim`, `s`.`activity_id`, `s`.`object_id`, `s`.`object_id_prim`, `s`.`hashtags`, `s`.`details`, `s`.`source`, `s`.`instances`, `s`.`attachments`, `s`.`cache`, `s`.`creation`, `s`.`local`, `s`.`filter_duplicate`, `ca`.`id` AS `cacheactor_id`, `ca`.`nid` AS `cacheactor_nid`, `ca`.`type` AS `cacheactor_type`, `ca`.`icon_id` AS `cacheactor_icon_id`, `ca`.`account` AS `cacheactor_account`, `ca`.`following` AS `cacheactor_following`, `ca`.`followers` AS `cacheactor_followers`, `ca`.`inbox` AS `cacheactor_inbox`, `ca`.`shared_inbox` AS `cacheactor_shared_inbox`, `ca`.`outbox` AS `cacheactor_outbox`, `ca`.`featured` AS `cacheactor_featured`, `ca`.`url` AS `cacheactor_url`, `ca`.`preferred_username` AS `cacheactor_preferred_username`, `ca`.`name` AS `cacheactor_name`, `ca`.`summary` AS `cacheactor_summary`, `ca`.`public_key` AS `cacheactor_public_key`, `ca`.`source` AS `cacheactor_source`, `ca`.`details` AS `cacheactor_details`, `ca`.`creation` AS `cacheactor_creation`, `ca`.`local` AS `cacheactor_local`, `cacd`.`id` AS `cacheactor_cachedocument_id`, `cacd`.`type` AS `cacheactor_cachedocument_type`, `cacd`.`mime_type` AS `cacheactor_cachedocument_mime_type`, `cacd`.`media_type` AS `cacheactor_cachedocument_media_type`, `cacd`.`url` AS `cacheactor_cachedocument_url`, `cacd`.`local_copy` AS `cacheactor_cachedocument_local_copy`, `cacd`.`resized_copy` AS `cacheactor_cachedocument_resized_copy`, `cacd`.`caching` AS `cacheactor_cachedocument_caching`, `cacd`.`public` AS `cacheactor_cachedocument_public`, `cacd`.`error` AS `cacheactor_cachedocument_error`, `cacd`.`creation` AS `cacheactor_cachedocument_creation`, `sa`.`id` AS `streamaction_id`, `sa`.`actor_id` AS `streamaction_actor_id`, `sa`.`stream_id` AS `streamaction_stream_id`, `sa`.`liked` AS `streamaction_liked`, `sa`.`boosted` AS `streamaction_boosted`, `sa`.`replied` AS `streamaction_replied` FROM `*PREFIX*social_stream` `s` INNER JOIN `*PREFIX*social_cache_actor` `ca` ON `ca`.`id_prim` = `s`.`attributed_to_prim` LEFT JOIN `*PREFIX*social_cache_doc` `cacd` ON `ca`.`icon_id` = `cacd`.`id_prim` LEFT JOIN `*PREFIX*social_stream_act` `sa` ON (`sa`.`actor_id_prim` = :dcValue5) AND ((`sa`.`stream_id_prim` = `s`.`id_prim`) OR (`sa`.`stream_id_prim` = `s`.`object_id_prim`)), `*PREFIX*social_stream_dest` `sd` WHERE (`s`.`type` = :dcValue1) AND (`s`.`attributed_to_prim` = :dcValue2) AND ((`sd`.`stream_id` = `s`.`id_prim`) AND (`sd`.`type` = :dcValue3)) AND ((`sd`.`stream_id` = `s`.`id_prim`) AND (`sd`.`type` = :dcValue4)) ORDER BY `s`.`nid` desc LIMIT 15",
    "columns": "[\"cacheactor_cachedocument_mime_type\",\"cacheactor_cachedocument_media_type\",\"cacheactor_cachedocument_local_copy\",\"cacheactor_cachedocument_resized_copy\",\"cacheactor_cachedocument_caching\",\"cacheactor_cachedocument_public\",\"cacheactor_cachedocument_creation\"]",
    "exception": "{\"class\":\"Doctrine\\DBAL\\Query\\QueryException\",\"message\":\"More than 30 characters for an output column name are not allowed on Oracle.\",\"code\":0,\"file\":\"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php:212\",\"trace\":\"#0 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(256): OC\\DB\\QueryBuilder\\QueryBuilder->prepareForExecute()\\n#1 /var/www/nextcloud/apps/social/lib/Tools/Db/ExtendedQueryBuilder.php(491): OC\\DB\\QueryBuilder\\QueryBuilder->executeQuery()\\n#2 /var/www/nextcloud/apps/social/lib/Db/StreamRequestBuilder.php(167): OCA\\Social\\Tools\\Db\\ExtendedQueryBuilder->getRows()\\n#3 /var/www/nextcloud/apps/social/lib/Db/StreamRequest.php(527): OCA\\Social\\Db\\StreamRequestBuilder->getStreamsFromRequest()\\n#4 /var/www/nextcloud/apps/social/lib/Db/StreamRequest.php(413): OCA\\Social\\Db\\StreamRequest->getTimelineAccount()\\n#5 /var/www/nextcloud/apps/social/lib/Service/StreamService.php(440): OCA\\Social\\Db\\StreamRequest->getTimeline()\\n#6 /var/www/nextcloud/apps/social/lib/Controller/ApiController.php(638): OCA\\Social\\Service\\StreamService->getTimeline()\\n#7 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(165): OCA\\Social\\Controller\\ApiController->accountStatuses()\\n#8 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(78): OC\\AppFramework\\Http\\Dispatcher->executeController()\\n#9 /var/www/nextcloud/lib/private/AppFramework/App.php(137): OC\\AppFramework\\Http\\Dispatcher->dispatch()\\n#10 /var/www/nextcloud/lib/private/Route/Router.php(324): OC\\AppFramework\\App::main()\\n#11 /var/www/nextcloud/lib/base.php(1159): OC\\Route\\Router->match()\\n#12 /var/www/nextcloud/index.php(25): OC::handleRequest()\\n#13 {main}\"}",
    "CustomMessage": "More than 30 characters for an output column name are not allowed on Oracle."
  },
  "id": "6a47a439b58ea"
}
```

**Comment by noci2012** [comment]
ow... the fix might have missed the upload to the main site.
